config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #resources :publications
  get '/', to: 'generals#index', as: 'index'
  get '/sign_up', to: 'accounts#sign_up', as: 'signup'
  #post '/publication/modify/:id', to: 'publications#edit'
  get '/publication/modify/:id', to: 'publications#edit', as: 'edit'
  post '/publication/modify/:id', to: 'publications#editform', as: 'editform'
  get 'publication/modify/:id', to: 'publications#update'
  post 'publication/modify/:id', to: 'publications#edit'
  get 'publication/modify/:id', to: 'publications#update'
  patch 'publication/modify/:id', to: 'publications#update', as: 'modifier'
  #post '/publication_edited/:id', to: 'accounts#update', as: 'editform'
  post '/sign_up_form', to: 'accounts#sign_up_form', as: 'signupform'
  post '/login', to: 'accounts#login', as: 'login'
  get '/publication', to: 'accounts#create_publication', as: "newpub"
  post '/publication', to: 'accounts#create_publication_form', as: 'pubcreate'
  post '/commentaire', to: 'accounts#comment', as: 'comment'
  get '/dashboard', to: 'accounts#dashboard', as: 'dashboard'
  delete '/logout', to: 'accounts#destroy', as: 'destroy'
  get 'publication/confirm', to: 'accounts#confirm', as: 'confirm'
  post 'publication/confirm', to: 'accounts#confirm', as: 'confirme'
  get  '*path', controller: 'application', action: 'render_404'
  post '*path', controller: 'application', action: 'render_404'
  get  '*path', controller: 'application', action: 'render_500'
  post '*path', controller: 'application', action: 'render_500'
  delete '/publication/:id', to: 'accounts#destroy_pub', as: 'destroypub'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commentaire.rb
class Commentaire < ApplicationRecord
	belongs_to :user
	belongs_to :publication
	validates :content, length: { in: 1..255 }
end

app/models/publication.rb
class Publication < ApplicationRecord
	belongs_to :user
	has_many :commentaires, :dependent => :delete_all
	mount_uploader :image, ImageUploader
	validates :content, length: { in: 1..255 }
end

app/models/user.rb
class User < ApplicationRecord

  has_many :publications
  has_many :commentaires
  validates :last_name, presence: true, length: { maximum: 30 }
  validates :first_name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, uniqueness: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, length: { in: 6..10 }, confirmation: true
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	before_action :authenticate_user!, only: [ :dashboard]
	before_action :authenticate_user!, only: [ :new, :create,  ]
	def sign_up
		@user = User.new
		render "accounts/index"
	end
	def sign_up_form
		@user = User.new(user_params)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to '/dashboard'
    else
      flash[:register_errors] = @user.errors.full_messages
      redirect_to '/sign_up'
    end
	end
	def login
		@user = User.find_by(email:login_params[:email])
    if @user && @user.authenticate(login_params[:password])
      session[:current_user_id] = @user.id
      redirect_to '/dashboard'
    else
      flash[:login_errors] = ['User Name or Password is not correct']
      redirect_to '/'
    end
	end
	def destroy
    session[:user_id] = nil
    flash[:notice] = "You have successfully logged out."
    redirect_to '/'
  end
  def update
  	@publication = Publication.find(params[:id])
  	if @publication.update(image: params[:image], content: params[:content])
  		redirect_to '/dashboard'
  	else
  		render "accounts/edit"
  	end
  end
	def edit
		@publication = Publication.find(params[:id])
	end
	def dashboard
		@user = User.find_by(id:session[:current_user_id])
		@publications = Publication.all
		@publication = Publication.new
		@comment = Commentaire.new
		@commentaires = Commentaire.all
		@users = User.all
		render "accounts/dashboard", layout: "layout"
	end
	def create_publication_form
		@publication = Publication.new(pub_params)
		render "accounts/confirm"
	end
	def confirm_get
		@publication = Publication.new(pub_params)
		render "accounts/confirm"
	end
	def confirm
		@publication = Publication.new(pub_params)
		@publication.user_id = session[:current_user_id]
		@publication.published_at = Time.now
		if @publication.save
			session[:current_publication_id] = @publication.id
			flash[:register_pub_success] = "Post publié avec succès"
      redirect_to '/dashboard'
    else
      flash[:register_pub_errors] = @publication.errors.full_messages
      redirect_to '/dashboard'
    end
	end
	def comment
		@comment = Commentaire.new(comment_params)
		@comment.user_id = session[:current_user_id]
		@comment.published_at = Time.now
		@comment.publication_id = session[:current_publication_id]
		if @comment.save
			flash[:register_comment] = "Commentaire publié avec succès"
      redirect_to '/dashboard'
    else
      flash[:register_comment_errors] = @comment.errors.full_messages
      redirect_to '/dashboard'
    end
  end
  def destroy_pub
    @publication = Publication.find(params[:id])
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_url }
      format.json { head :no_content }
    end
  end
	private
		def user_params
			params.require(:user).permit(:last_name, :first_name, :email, :gender, :date_of_birth, :password)
		end
		def login_params
      params.require(:login).permit(:email, :password )
    end
    def pub_params
      params.require(:publication).permit(:image, :content)
    end
    def pub2_params
      params.require(:publication).permit(:content)
    end
    def comment_params
      params.require(:comment).permit(:content )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from Exception, with: :render_500
  
  def render_404
    render template: 'errors/error_404', status: 404, layout: 'application', content_type: 'text/html'
  end
  
  def render_500
    render template: 'errors/error_500', status: 500, layout: 'application', content_type: 'text/html'
  end
end

app/controllers/generals_controller.rb
class GeneralsController < ApplicationController
    def index
        @user = User.new
    end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
	def edit
		@publication = Publication.find(params[:id])
		render "accounts/edit"
	end
	def editform
		@publication = Publication.find(params[:id])
		if @publication.update(pub_params)
			flash[:pub_update] = "Post mis à jour avec succès"
			redirect_to '/dashboard'
		else
			flash[:pub_update_errors] = @publication.errors.full_messages
  			redirect_to edit_path(@publication)
  		end
	end

	private
		def pub_params
	      params.require(:publication).permit(:image, :content)
	    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/generals_helper.rb
module GeneralsHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/accounts/confirm.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
        rel="stylesheet"
      />
      <!-- Google Fonts -->
      <link
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        rel="stylesheet"
      />
      <!-- MDB -->
      <link
        href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
        rel="stylesheet"
      />
    <title>Confirmation</title>
  </head>
  <body>
    <div class="container mt-44">
        <h2 class="text-center mb-8">Confirmer votre Publlication</h2>
      <div class="row mt-48 text-center">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
          <img src="<%= @publication.image %>"> <hr>
          <br>
          <%= @publication.content %>
        </div>
        <div class="col-md-4">
        </div>
        <%= form_with(model: @publication, local: true, url: confirme_path) do |form| %>
        <%= form.hidden_field :image %>
        <%= form.hidden_field :content %>
        <%= form.submit %>
        <% end %>
      </div>
    </div>
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
    ></script>
  </body>
</html>

app/views/accounts/dashboard.html.erb
<% content_for :content do %>
  <% @publications.each do |publication| %>
    <div class="card mb-3">
        <p class="card-text mt-3">
            &nbsp;&nbsp;&nbsp;
          <i class="fas fa-user"></i>
            &nbsp;
            <% @users.each do |usere| %>
              <% if publication.user_id == usere.id %>
                  <%= usere.last_name %>&nbsp;
                  <%= usere.first_name %>
              <% end %>
            <% end %>
            </p>
         <img
          src="<%= publication.image %>"
          class="card-img-top"
          alt="..."/>
        <div class="card-body">
          <p class="card-text text-center" style="margin-top: -15px;">
            <%= publication.content %></p>
          <div class="row">
            <div class="col-6 ">
              <p class="card-text">
                <small class="text-muted">Publié le <%= publication.published_at %></small>
              </p>
              <br>
              <div class="card-body"><h5>Commentaires</h5>
              <% @commentaires.each do |commentaire| %>
                <% if publication.id == commentaire.publication_id %>
                  <div class="card-body">
                    <i class="fas fa-user"></i> &nbsp;
                    <% @users.each do |useri| %>

                        <% if useri.id == commentaire.user_id %>
                          <%= useri.last_name %>
                        <% end %>
                    <% end %>
                    <br>
                        <%= commentaire.content %>
                  </div>
                <% end %>
              <% end %></div>
            </div>
            <div class="col-6 text-end" style=" text-align: right;">
                <% if publication.user_id == @user.id %>
                      <button class="btn btn-warning" data-mdb-toggle="modal"
                      data-mdb-target="#comment">Commenter</button>
                        <br><br><%= link_to 'Modifier', edit_path(publication), class: "btn btn-success" %>
                  &nbsp;
                  <%= link_to 'Supprimer', destroypub_path(publication), class: "btn btn-danger",  :method => :delete, :confirm => "Are you sure?" %>
                <% else %>
                  <button class="btn btn-warning" data-mdb-toggle="modal"
                      data-mdb-target="#comment">Commenter</button>
                <% end %>
            </div>
          </div>
        </div>
    </div>
    <br>
    <hr>
    <br><br>
  <% end %>
<% end %>

app/views/accounts/edit.html.erb
  <%= form_with( method: "post", model:@publication, local: true, url: editform_path) do |form| %>
    <div class="form-outline mb-4">
      <%= image_tag(@publication.image.url) if @publication.image && @publication.image.url %>
      <%= form.file_field :image, class: "form-control" %>
    </div>
    <div class="form-outline mb-4">
      <%= form.label :content, "Publication", class: "form-label" %> <br>
      <%= form.text_area :content, size: "70x5", class: "form-control" %>
    </div>
    <div class="text-center">
      <%= form.submit "Publier", class: "btn btn-success  mb-4", style: "padding-right: 50px; padding-left: 50px; font-size: 17px;" %>
    </div>
  <% end %>

app/views/accounts/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <meta name="description" content="" />
      <meta name="author" content="" />
      <title> Facebook - Connexion ou Inscription </title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
      <link
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        rel="stylesheet" />
      <link
        href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
        rel="stylesheet" />
  </head>
  <body style="background-color: #F0F2F5;">
    <div class="container" >
      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
          <div class="text-center">
              <img class="img-fluid" style="width: 60%; margin-bottom: -15px; margin-left: -35px;" src="https://static.xx.fbcdn.net/rsrc.php/y8/r/dF5SId3UHWd.svg" alt="Facebook">
            </div>
        </div>  
      </div>
      <div class="row " style="margin-top: px;">
        <div class="col-md-3"></div>
        <div class="col-md-6" style="margin-top: 0px; ">
          <div class="card">
            <div class="card-body ">
              <div class="errors">
                    <% if flash[:register_errors]%>
                      <% flash[:register_errors].each do |error| %>
                        <p class="alert alert-danger"> <%=error%></p>
                      <%end%>
                    <%end%>
                  </div>
              <%= form_with(model: @user, url: signupform_path, method: "post") do |form| %>
                <div class="row mb-4">
                  <div class="col">
                    <div class="form-outline">
                      <%= form.text_field :first_name, class: "form-control" %>
                      <%= form.label :first_name, "Prénoms", class: "form-label" %>
                    </div>
                  </div>
                  <div class="col">
                    <div class="form-outline">
                      <%= form.text_field :last_name, class: "form-control" %>
                      <%= form.label :last_name, "Noms", class: "form-label" %>
                    </div>
                  </div>
                </div>
                <div class="form-outline mb-4">
                  <%= form.email_field :email, class: "form-control" %>
                  <%= form.label :email, "Adresse e-mail", class: "form-label" %>
                </div>  
                <div class="row ">
                  <div class="col">
                    <div class="form-outline mb-4">
                      <%= form.password_field :password, class: "form-control" %>
                      <%= form.label :password, "Mot de passe", class: "form-label" %>
                    </div>
                  </div>
                  <div class="col">
                    <div class="form-outline ">
                      <%= form.password_field :password_confirmation, class: "form-control" %>
                      <%= form.label :password_confirmation, "Confirmez le mot de passe", class: "form-label" %>
                    </div>
                  </div>
              </div>
              <div class="form-outline mb-4">
                  <%= form.date_field :date_of_birth, class: "form-control" %>
                  <%= form.label :date_of_birth, "Date d'anniversaire", class: "form-label" %>
              </div>
              <div class="text-center mb-4">
                <p style="text-align: left;">Votre sexe:</p>
                <div class="form-check form-check-inline">
                  <%= form.radio_button :gender, "F", class: "form-check-input" %>
                  <%= form.label :gender_f, "Féminin" , class: "form-check-label"%>
                </div>
                <div class="form-check form-check-inline">
                  <%= form.radio_button :gender, "M" , class: "form-check-input"%>
                  <%= form.label :gender_m, "Masculin", class: "form-check-label" %>
                </div>
              </div>
              <div class="text-center">
                <%= form.submit "S'inscrire", class: "btn btn-success  mb-4", style: "padding-right: 50px; padding-left: 50px; font-size: 17px;" %>
              <% end %>
              </div>
            </div>
          </div>
          <br>
          <p class="text-center">Créer une Page pour une célébrité, un groupe ou une entreprise.</p>
        </div>
        <div class="col-md-3"></div>
      </div>
    </div>
    <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
    ></script>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/layout.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Dashboard</title>
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="css/style2.css">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
</head>
<body>
    <div
      class="modal fade"
      id="publication"
      data-mdb-backdrop="static"
      data-mdb-keyboard="false"
      tabindex="-1"
      aria-labelledby="staticBackdropLabel"
      aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
           <h5 class="modal-title" id="staticBackdropLabel" style="font-weight: bolder;">Nouvelle publication</h5>
            <button
              type="button"
              class="btn-close"
              data-mdb-dismiss="modal"
              aria-label="Close"
            ></button>
          </div>
          <div class="modal-body">
            <%= form_with(model: @publication, url: pubcreate_path, method: "post") do |form| %>
                <div class="form-outline mb-4">
                <%= form.label :image, "Ajouter une photo(optionnel)", class: "form-label" %>
                <%= image_tag(@publication.image.url) if @publication.image && @publication.image.url %>
                  <%= form.file_field :image, class: "form-control" %>
                </div>
                <div class="form-outline mb-4">
                    <%= form.label :content, "Publication", class: "form-label" %>
                  <%= form.text_area :content, size: "70x5", class: "form-control" %>
                </div>
              <div class="text-center">
                <%= form.submit "Publier", class: "btn btn-success  mb-4", style: "padding-right: 50px; padding-left: 50px; font-size: 17px;" %>
              <% end %>
              </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-mdb-dismiss="modal">
              Annuler
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3 style="font-weight: bold;">Facebook</h3>
            </div>
            <ul class="list-unstyled components">
                <p style="font-weight: bold;"></p>
                <li>
                    <a href="#pageSubmenue" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Publications</a>
                    <ul class="collapse list-unstyled" id="pageSubmenue">
                        <li>
                            <a href="">Mes publications</a>
                        </li>
                        <li>
                            <a href="">Voir toutes les publications</a>
                        </li>

                    </ul>
                </li>
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Mon compte</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="">Profil</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <ul class="list-unstyled " style="margin-top: 250px;">

                <li >
                    <a href="" data-toggle="collapse" aria-expanded="false" class="btn btn-success" data-mdb-toggle="modal"
                data-mdb-target="#publication">Nouvelle publication</a>
                </li>
            </ul>
        </nav>
        <div id="content">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-primary">
                        <i class="fas fa-align-left"></i>
                        <span></span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item ">
                                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"
                                > <%= @user.last_name %>
                                &nbsp; <%= @user.first_name %>  </a>
                            </li>&nbsp;
                            <li class="nav-item">
                                <%= button_to "Se déconnecter", destroy_path, method: :delete, class: "btn btn-warning  ", style: "padding-right:px; padding-left: px; font-size: 17px;" %>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="errors">
                    <% if flash[:register_pub_errors]%>
                      <% flash[:register_pub_errors].each do |error| %>
                        <p class="alert alert-danger"> <%=error%></p>
                      <%end%>
                    <%end%>
            </div>
            <div class="errors">
                    <% if flash[:register_pub_success]%>
                        <p class="alert alert-success"> <%= flash[:register_pub_success]%></p>
                    <%end%>
                    <% if flash[:pub_update]%>
                        <p class="alert alert-success"> <%= flash[:pub_update]%></p>
                    <%end%>
            </div>
            <div class="errors">
                    <% if flash[:register_comment]%>
                        <p class="alert alert-success"> <%= flash[:register_comment]%></p>
                    <%end%>
            </div>
            <div class="errors">
                    <% if flash[:register_comment_errors]%>
                      <% flash[:register_comment_errors].each do |error| %>
                        <p class="alert alert-danger"> <%=error%></p>
                      <%end%>
                    <%end%>
            </div>
            <%= yield :content %>
        </div>
    </div>
    <div
      class="modal fade"
      id="comment"
      data-mdb-backdrop="static"
      data-mdb-keyboard="false"
      tabindex="-1"
      aria-labelledby="staticBackdropLabel"
      aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
           <h5 class="modal-title" id="staticBackdropLabel" style="font-weight: bolder;">Votre commentaire</h5>
            <button
              type="button"
              class="btn-close"
              data-mdb-dismiss="modal"
              aria-label="Close"
            ></button>
          </div>
          <div class="modal-body">
            <%= form_with(url: comment_path, method: "post") do |form| %>
                <div class="form-outline mb-8">
                    <textarea class="form-control" name="comment[content]"></textarea>
                </div>
                <br><br>
              <div class="text-center">
                <%= form.submit "Commenter", class: "btn btn-success  mb-4", style: "padding-right: 50px; padding-left: 50px; font-size: 17px;" %>
              </div>
            <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-mdb-dismiss="modal">
              Annuler
            </button>

          </div>
        </div>
      </div>
    </div>
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
    ></script>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>
</body>

</html>